name: flutter_mautic
description: "A Flutter package that provides easy integration with the Mautic API to manage contacts and track user events in your app."
version: 0.0.1
homepage: https://github.com/mrehman29/flutter_mautic

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.16
  http_mock_adapter: ^0.6.1
