name: flutter_mautic
description: "Flutter Mautic provides seamless integration with the Mautic API, allowing Flutter developers to easily manage contacts, campaigns, and custom fields within their apps. This package simplifies operations such as adding or removing contacts from campaigns, updating contact fields, and retrieving Mautic data, offering a convenient, secure way to interact with Mautic's CRM functionalities directly from Flutter."
version: 0.0.1
homepage: https://github.com/mrehman29/flutter_mautic

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.16
  http_mock_adapter: ^0.6.1
